{"name": "multiply_-pythoncode_9", "status": "failed", "statusDetails": {"message": "AssertionError: assert -9 == '-pythoncode-...de-pythoncode'\n  +-9\n  -'-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode'", "trace": "self = <testing.test_Calculator.TestCalc object at 0x000001564F49C088>, get_instance = <pythoncode.Calculator.Calculator object at 0x000001564F452548>, get_multiply_int_datas_with_fixture = ['-pythoncode', 9, -9]\n\n    @allure.title(\"multiply_{get_multiply_int_datas_with_fixture[0]}_{get_multiply_int_datas_with_fixture[1]}\")\n    @allure.story(\"multiply Integer Function\")\n    def test_multiply_int(self, get_instance, get_multiply_int_datas_with_fixture):\n        multiply_int = get_multiply_int_datas_with_fixture\n>       assert multiply_int[2] == get_instance.multiply(multiply_int[0], multiply_int[1])\nE       AssertionError: assert -9 == '-pythoncode-...de-pythoncode'\nE         +-9\nE         -'-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode-pythoncode'\n\ntest_Calculator.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "26c6fb69-cd49-42e7-bf4b-4cee7aa6fe2d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_multiply_int_datas_with_fixture", "value": "['-pythoncode', 9, -9]"}], "start": 1612420386919, "stop": 1612420386920, "uuid": "bf4c043e-d90a-4c0c-9b4a-e2c09d50ac55", "historyId": "147809acfe5d9789dc54d9801da5cd29", "testCaseId": "74ae4a99e2b1463598db95f6c0fec520", "fullName": "test_Calculator.TestCalc#test_multiply_int", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "multiply Integer Function"}, {"name": "suite", "value": "test_Calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-ALON4FT"}, {"name": "thread", "value": "10176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Calculator"}]}