{"name": "multiply_3_pythoncode", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 'pythoncodepy...odepythoncode'\n  +3\n  -'pythoncodepythoncodepythoncode'", "trace": "self = <testing.test_Calculator.TestCalc object at 0x000001564F469788>, get_instance = <pythoncode.Calculator.Calculator object at 0x000001564F469888>, get_multiply_int_datas_with_fixture = [3, 'pythoncode', 3]\n\n    @allure.title(\"multiply_{get_multiply_int_datas_with_fixture[0]}_{get_multiply_int_datas_with_fixture[1]}\")\n    @allure.story(\"multiply Integer Function\")\n    def test_multiply_int(self, get_instance, get_multiply_int_datas_with_fixture):\n        multiply_int = get_multiply_int_datas_with_fixture\n>       assert multiply_int[2] == get_instance.multiply(multiply_int[0], multiply_int[1])\nE       AssertionError: assert 3 == 'pythoncodepy...odepythoncode'\nE         +3\nE         -'pythoncodepythoncodepythoncode'\n\ntest_Calculator.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "214ba126-4c0f-49c3-9c47-f16ed59b1019-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_multiply_int_datas_with_fixture", "value": "[3, 'pythoncode', 3]"}], "start": 1612420386902, "stop": 1612420386902, "uuid": "d98b7bd6-c848-4872-af20-3c691e2be224", "historyId": "005884391cac43213e0d8b622a3a7526", "testCaseId": "74ae4a99e2b1463598db95f6c0fec520", "fullName": "test_Calculator.TestCalc#test_multiply_int", "labels": [{"name": "feature", "value": "计算器"}, {"name": "story", "value": "multiply Integer Function"}, {"name": "suite", "value": "test_Calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-ALON4FT"}, {"name": "thread", "value": "10176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Calculator"}]}