{"name": "multiply_3000_2000", "status": "failed", "statusDetails": {"message": "AssertionError: assert 60000000 == 6000000", "trace": "self = <testing.test_Calculator.TestCalc object at 0x0000021C3BC0F548>\nget_instance = <pythoncode.Calculator.Calculator object at 0x0000021C3BC11AC8>\nget_multiply_int_datas_with_fixture = [3000, 2000, 60000000]\n\n    @allure.title(\"multiply_{get_multiply_int_datas_with_fixture[0]}_{get_multiply_int_datas_with_fixture[1]}\")\n    @allure.story(\"multiply Integer Function\")\n    def test_multiply_int(self, get_instance, get_multiply_int_datas_with_fixture):\n        multiply_int = get_multiply_int_datas_with_fixture\n>       assert multiply_int[2] == get_instance.multiply(multiply_int[0], multiply_int[1])\nE       assert 60000000 == 6000000\n\ntest_Calculator.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "66f824c1-e3bf-4a52-b360-4648e5633220-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_multiply_int_datas_with_fixture", "value": "[3000, 2000, 60000000]"}], "start": 1612411131276, "stop": 1612411131277, "uuid": "e17707c9-6dbb-4693-8591-837390dc7da1", "historyId": "dd34b1cccd21045bf2ad03024137e43a", "testCaseId": "74ae4a99e2b1463598db95f6c0fec520", "fullName": "test_Calculator.TestCalc#test_multiply_int", "labels": [{"name": "story", "value": "multiply Integer Function"}, {"name": "feature", "value": "计算器"}, {"name": "suite", "value": "test_Calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-ALON4FT"}, {"name": "thread", "value": "22632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Calculator"}]}