{"name": "multiply_3_pythoncode", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 'pythoncodepythoncodepythoncode'", "trace": "self = <testing.test_Calculator.TestCalc object at 0x000001E37D3E1148>\nget_instance = <pythoncode.Calculator.Calculator object at 0x000001E37D3E3788>\nget_multiply_int_datas_with_fixture = [3, 'pythoncode', 3]\n\n    @allure.title(\"multiply_{get_multiply_int_datas_with_fixture[0]}_{get_multiply_int_datas_with_fixture[1]}\")\n    @allure.story(\"multiply Integer Function\")\n    def test_multiply_int(self, get_instance, get_multiply_int_datas_with_fixture):\n        multiply_int = get_multiply_int_datas_with_fixture\n>       assert multiply_int[2] == get_instance.multiply(multiply_int[0], multiply_int[1])\nE       AssertionError: assert 3 == 'pythoncodepythoncodepythoncode'\n\ntest_Calculator.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "18055660-2c77-4e76-8b7c-e6a2d5416df1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_multiply_int_datas_with_fixture", "value": "[3, 'pythoncode', 3]"}], "start": 1612419968114, "stop": 1612419968114, "uuid": "3cfc0ea6-ec38-467a-94aa-123f4bfc3314", "historyId": "005884391cac43213e0d8b622a3a7526", "testCaseId": "74ae4a99e2b1463598db95f6c0fec520", "fullName": "test_Calculator.TestCalc#test_multiply_int", "labels": [{"name": "story", "value": "multiply Integer Function"}, {"name": "feature", "value": "计算器"}, {"name": "suite", "value": "test_Calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-ALON4FT"}, {"name": "thread", "value": "19128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Calculator"}]}